title: "Max Emes Typographic Blog "
description: ""
header_text: "Typographic Blog "
footer_text: Copyright 2020 Your name
header_feature_image: ../uploads/typography-.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
